name: Deploy Laravel Application

on:
  push:
    branches:
      - main # ou o nome do branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # ou a versão que você está usando
          extensions: mbstring, sqlite3, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Build assets
        run: npm install && npm run production

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /path/to/your/project
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            npm install && npm run production
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
